version: '3.3'
services:
  pengu_app:
    container_name: pengus-app
    image: pengus-app
    build:
      context: ../../../
      dockerfile: src/main/docker/Dockerfile.jvm
    links:
      - postgres
    environment:
      - DB_HOST=postgres
    ports:
      - 8083:8083

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=penguins
      - POSTGRES_USER=penguins
      - POSTGRES_DB=penguins
    ports:
      - "5432:5432"
